SELECT 
	A.CORP_CODE,
	A.FACTORY_CODE,
	A.LOCATION_NAME ,
	A.LOCATION_ID,
	A.LOCATION_GUBUN ,
	B.RACK_NUMBER,
	B.BARCODE 
FROM 
	TB_MOLD_LOCATION A  with(nolock)
JOIN
	TB_RACK B 
ON
	B.RACK_NUMBER  = A.LOCATION_ID 
