DECLARE @vTEMP_TABLE TABLE
(
	CORP_CODE 	nvarchar(30)
, 	FACTORY_CODE nvarchar(30)
, 	RFID 		nvarchar(30)
,	STATE		nvarchar(10)	
,	DT			nvarchar(8)
,	SEQ			int
,   GUBUN		nvarchar(30)
,   POSITION	nvarchar(30)
,	POSITION_DETIAL nvarchar(30)
,	MOLD_NAME nvarchar(30)
,	POSITION_NAME nvarchar(30)
,	GUBUN_NAME nvarchar(30)
,	POSITION_DETAIL_NAME  nvarchar(30)
)

INSERT INTO @vTEMP_TABLE EXEC SP_MOLD_IN_ABLE 
SELECT DISTINCT 
	A.CORP_CODE
	,A.FACTORY_CODE
	,A.RFID
	,A.GUBUN
	,A.POSITION
	,B.BARCODE AS LOCATION_BARCODE
	,B.LOCATION_NAME 
	,C.BARCODE AS RACK_BARCODE
	,D.MOLD_NAME 
	,D.CAVITY 
	,D.TON 
FROM
	@vTEMP_TABLE  AS A 
LEFT JOIN 
	TB_MOLD_LOCATION B 
	ON 	B.CORP_CODE = A.CORP_CODE 
	AND B.FACTORY_CODE = A.FACTORY_CODE 
	AND B.LOCATION_GUBUN = A. GUBUN
	AND B.LOCATION_ID = A.POSITION
LEFT JOIN 
	TB_RACK C
	ON C.CORP_CODE  = A.CORP_CODE
	AND  C.FACTORY_CODE=  A.FACTORY_CODE
	AND C.RACK_CODE = A.POSITION_DETIAL
LEFT JOIN 
	TB_MOLD D
	ON  D.CORP_CODE  = A.CORP_CODE
	AND D.FACTORY_CODE = A.FACTORY_CODE
	AND CONVERT (NUMERIC,D.RFID) =CONVERT (NUMERIC,A.RFID)