DECLARE  @vCYCLE_NO VARCHAR(20) , @vDATE VARCHAR(20)
SET @vDATE = CONVERT(CHAR(10), GETDATE() , 23)
SET @vCYCLE_NO =(SELECT 
TOP 1
A.CYCLE_NO  
FROM 
   TB_SENSOR_DATA_PRESSURE  A with(nolock)
WHERE 
    A.MACHINE_TYPE =@MACHINE_TYPE
    AND A.MACHINE_ID =@MACHINE_ID
    AND A.KEY_DT = @vDATE
    ORDER BY A.COLLECT_DT DESC)

SELECT 
	A.CYCLE_NO ,
	D.MACHINE_TYPE ,
	D.MACHINE_ID ,
	A.VALUE ,
	A.DATA_TYPE,
	A.COLLECT_DT,
	D.CH_NAME ,
	B.UPPER_LIMIT ,
	B.LOWER_LIMIT 
FROM 
   TB_SENSOR_DATA_PRESSURE  A  with(nolock)
JOIN 
   TB_SENSOR_CHANNEL_INFO D 
   ON D.MACHINE_TYPE  =A.MACHINE_TYPE 
   AND D.MACHINE_ID =A.MACHINE_ID 
   AND D.CH_GROUP = A.CH_GROUP 
   AND D.CH_NAME LIKE '%P%'
   AND D.CH_NAME = @CH_NAME
JOIN 
	TB_SENSOR_REALTIME_LIMIT B 
	ON B.MACHINE_TYPE  = A.MACHINE_TYPE 
	AND B.MACHINE_ID  = A.MACHINE_ID 
	AND B.DATA_TYPE  = A.DATA_TYPE 
	AND B.CH_GROUP = D.CH_GROUP 
WHERE 
   A.CYCLE_NO BETWEEN CONVERT (int,'0' )AND CONVERT (int,@vCYCLE_NO ) 
   AND A.DATA_TYPE ='Integral_Pressure'
   AND A.MACHINE_ID = @MACHINE_ID
   AND A.MACHINE_TYPE = @MACHINE_TYPE
   AND A.KEY_DT = @vDATE
  ORDER BY len (A.CYCLE_NO) ASC, A.CYCLE_NO ASC , A.COLLECT_DT ASC , A.CH_GROUP ASC