SELECT DISTINCT
	A.RFID 
  , A.MACHINE_ID 
  , B.MOLD_NAME 
  , A.DATA_TYPE 
  , A.MESSAGE 
  , A.CH_NAME
  , A.[DATE] AS  COLLECT_DT
  , A.VALUE 
  , A.LIMIT_VALUE 

FROM 
   TB_SENSOR_ALARM A  with(nolock)
JOIN
   TB_MOLD B 
   ON CONVERT (NUMERIC,B.RFID) =CONVERT (NUMERIC,A.RFID)
