SELECT DISTINCT 
	A.MACHINE_TYPE ,
	A.MACHINE_ID,
	B.MACHINE_NAME ,
	B.MACHINE_LEGEND ,
	B.VIEW_STATUS ,
	B.CUR_MOLDFILE_NAME,
	C.IS_CONNECTED AS SENSOR_IS_ACTIVE 
FROM
 TB_SENSOR_CHANNEL_INFO A  with(nolock)
JOIN
 PI_SVR.dbo.REALTIME_LINKI B
ON
 B.MACHINE_ID = A.MACHINE_ID
JOIN
 TB_SENSOR_STATUS_INFO C 
ON
 C.MACHINE_ID = A.MACHINE_ID 
 