SELECT 
	A.RFID,
	A.CYCLE_NO ,
	D.MACHINE_TYPE ,
	D.MACHINE_ID ,
	A.VALUE ,
	A.DATA_TYPE,
	A.COLLECT_DT,
	D.CH_NAME ,
	B.UPPER_LIMIT ,
	B.LOWER_LIMIT 
FROM 
   TB_SENSOR_DATA_PRESSURE  A  with(nolock)
JOIN 
   TB_SENSOR_CHANNEL_INFO D 
   ON D.MACHINE_TYPE  =A.MACHINE_TYPE 
   AND D.MACHINE_ID =A.MACHINE_ID 
   AND D.CH_GROUP = A.CH_GROUP 
   AND D.CH_NAME LIKE '%P%'
JOIN 
	TB_SENSOR_DATA_LIMITS B 
	ON B.MACHINE_TYPE  = A.MACHINE_TYPE 
	AND B.DATA_TYPE  = A.DATA_TYPE 
	AND B.CH_GROUP = A.CH_GROUP 
	AND B.RFID = A.RFID
WHERE 
   A.DATA_TYPE ='Integral_Pressure'
   AND isnumeric(A.VALUE) = 1 
   AND A.MACHINE_ID = @MACHINE_ID
   AND A.RFID = @RFID
   AND CONVERT(CHAR(23), A.COLLECT_DT , 21) BETWEEN CAST(@START_DT AS Date) AND CAST(@END_DT AS Date)
   AND CAST (A.COLLECT_DT AS time(0)) BETWEEN CAST (@START_DT AS time(0)) AND CAST (@END_DT AS time(0))
   ORDER BY A.COLLECT_DT ASC 