DECLARE @vCYCLE_NO VARCHAR(20) , @vDATE VARCHAR(20)
SET @vDATE = CONVERT(CHAR(10), GETDATE() , 23)
SET @vCYCLE_NO =(SELECT 
TOP 1
A.CYCLE_NO  
FROM 
   TB_SENSOR_DATA_PRESSURE  A with(nolock)
WHERE 
    A.MACHINE_TYPE =@MACHINE_TYPE
    AND A.MACHINE_ID =@MACHINE_ID
    AND A.KEY_DT = @vDATE
    ORDER BY A.COLLECT_DT DESC)
    
SELECT 
   A.CYCLE_NO,
   A.MACHINE_ID,
   A.MACHINE_TYPE ,
   D.CH_NAME ,
   A.VALUE ,
   D.CH_GROUP ,
   A.DATA_TYPE ,
   A.COLLECT_DT,
   D.COLOR 
FROM 
   TB_SENSOR_DATA_PRESSURE  A  with(nolock)
JOIN 
   TB_SENSOR_CHANNEL_INFO D 
   ON D.MACHINE_TYPE  =@MACHINE_TYPE
   AND D.MACHINE_ID =A.MACHINE_ID 
   AND D.CH_GROUP = A.CH_GROUP 
   AND D.CH_NAME LIKE '%P%'
   AND A.MACHINE_ID = @MACHINE_ID
WHERE 
    A.CYCLE_NO =@vCYCLE_NO 
    AND A.DATA_TYPE NOT IN ('MeasData_Pressure')
    AND A.DATA_TYPE NOT IN ('None')
   ORDER BY A.COLLECT_DT DESC