SELECT DISTINCT
    A.RFID
  , C.MACHINE_ID
  , B.MOLD_NAME
  , A.DATA_TYPE
  , A.MESSAGE
  , A.CH_NAME
  , A.[DATE] AS COLLECT_DT
  , A.VALUE
  , A.LIMIT_VALUE
FROM
   TB_SENSOR_ALARM A  with(nolock)
JOIN
   TB_MOLD B 
   ON CONVERT(NUMERIC, B.RFID) = CONVERT(NUMERIC, A.RFID)
JOIN
    TB_SENSOR_DATA_PRESSURE C 
    ON C.RFID = A.RFID
    AND C.MACHINE_ID  = A.MACHINE_ID 
WHERE
    A.RFID = @RFID
    AND CONVERT(CHAR(23), A.DATE , 21) BETWEEN CAST(@START_DT AS Date) AND CAST(@END_DT AS Date)
    AND CAST (A.DATE AS time(0)) BETWEEN CAST (@START_DT AS time(0)) AND CAST (@END_DT AS time(0))
    ORDER BY A.DATE ASC 
;
